
export * from "./mis.interface";
export * from "./Project.interface";
export * from "./project-view.interface";
export * from "./General-settings.interface";
export * from "./vouchers-interface/Sales-voucher.interface";
export * from "./Hrms.interface"
export * from "./Supplier.interface"
export * from "./IT-asset-mgmt.interface";
export * from "./opportunity-tracker.interface";
export * from "./Doc-center.interface";
export * from "./Resignation.interface";
export * from "./sale-user-view.interface";
export * from "./Locations.interface";
export * from "./Iinvoice.interface";
export * from "./assetLocation.interface";
export * from "./invoice_data.inerface";
export * from "./holiday-calender.interface";
export * from "./kpi/operational-kpi.interface";
export * from "./kpi/people-Kpi.interface";
export * from "./kpi/customer-kpi.interface";
export * from "./kpi/financial-kpi.interface";
export * from "./kpi/brand-kpi.interface";
export * from "./it-ticketing.inerface";
export * from "./User.interface";
export * from "./kpi/compliance-kpi.interface";
export * from "./appraisal.interface";
export * from "./Category.interface"
export * from "./User.interface";
export * from "./side-menu.interface";
export * from "./pdp.interface";
export * from "./dropdownOptions.interface";
export * from "./advisor.interface";
export * from "./nonDisplay-ledger.interface";
export * from "./percentage-target.interface";
export * from "./budget.interface"
export * from "./audit.interface"